# Generated by Django 3.1.1 on 2020-09-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200926_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='creared_date',
            new_name='created_date',
        ),
    ]
