# Generated by Django 3.1.1 on 2020-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200926_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='listed_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
