# Generated by Django 3.1.1 on 2020-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.IntegerField(),
        ),
    ]
